esphome:
  name: lightstrip
  platform: ESP8266
  board: nodemcu
  on_boot:
    then:
      - light.turn_on:
          id: lightstrip
          brightness: 0%
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 200ms
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lightstrip Fallback Hotspot"
    password: "Ot9YCmWurk5a"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


sensor:
  - platform: ultrasonic
    trigger_pin: D2
    echo_pin: D1
    name: "Ultrasonic Sensor"
    update_interval: 400ms
    on_raw_value:
      then:
        - light.turn_on:
            id: lightstrip
            brightness: !lambda |-
              ESP_LOGD("custom", "The value of sensor is: %f", x);
              if (x > 0.005 && x < 0.6) {
                ESP_LOGD("custom", "The corrected value is: %f", (0.6 - x) / 0.6);
                return (0.6 - x) / 0.6;
              } else {
                return 0.5;
              }

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D5
    id: lightstrip
    num_leds: 150
    rgb_order: GRB
    name: "FastLED WS2812B Light"